# INITIAL IMPORT

In [10]:
%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
from src.config import Configuration
from src.tetris import TetrisConfiguration

T_CONFIG = TetrisConfiguration(
    board_w=10,
    board_h=20,
)

CONFIG = Configuration(
    max_board_size_w=10,
    max_board_size_h=20,
)

# Game

In [12]:
from src.tetris import Board, PieceEnum, Queue, ActionEnum, ActivePiece, Tetris, RotationEnum, ROTATION_DIR

In [13]:
game = Tetris()
print('=== SPAWNED from queue ===')
game.print_state()

print('=== LEFT ===')
game.move_active_piece(ActionEnum.LEFT)
game.print_state()

print('=== RIGHT x2 ===')
game.move_active_piece(ActionEnum.RIGHT)
game.move_active_piece(ActionEnum.RIGHT)
game.print_state()

print('=== ROTATE CW ===')
game.move_active_piece(ActionEnum.ROTATE_CW)
game.print_state()

print('=== ROTATE 180 ===')
game.move_active_piece(ActionEnum.ROTATE_180)
game.print_state()

print('=== ROTATE CCW ===')
game.move_active_piece(ActionEnum.ROTATE_CCW)
game.print_state()

print('=== HOLD (swapped with hold slot) ===')
game.move_active_piece(ActionEnum.HOLD)
game.print_state()
print(f'piece={game.active_piece.type} can_hold={game.can_hold}\n')

print('=== DROP + LOCK + SPAWN next ===')
game.move_active_piece(ActionEnum.DROP)
game.print_state()
print(f'piece={game.active_piece.type} pos=({game.active_piece.x},{game.active_piece.y})\n')

print('=== HOLD again (swap back) ===')
lines =game.move_active_piece(ActionEnum.HOLD)
game.print_state()
print(f'piece={game.active_piece.type}\n')

print(f'=== DIRECT: hard_drop + lock_piece (cleared {lines} lines) ===')
lines = game.move_active_piece(ActionEnum.DROP)
game.print_state()
print()

print('=== BOARD: get_ghost_y + hard_drop ===')
gy = game.board.get_ghost_y(game.active_piece)
print(f'ghost Y from y={game.active_piece.y}: {gy}')
drop_dist = game.board.hard_drop(game.active_piece)
print(f'dropped {drop_dist} rows, now at y={game.active_piece.y}')
game.print_state()

=== SPAWNED from queue ===
Current Board:
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
Active Piece: L at (3, 20) with rotation SPAWN
Next Piece: I
Hold Piece: None
Can Hold: True
=== LEFT ===
Current Board:
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
Active Piece: L at (2, 20) with rotation SPAWN
Next Piece: I
Hold Piece: None
Can Hold: True
=== RIGHT x2 ===
Current Board:
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
Active Piece: L at (4, 20) with rotation SPAWN
Next 

# Move Searcher

In [14]:
from src.tetris import MoveSearcher

game = Tetris(
    # playfield='G'
#     playfield=''.join([
#         'GGNGGGGGGG',
#         'GGNGGGGGGG',
#         'GNNNGGGGGG',
#         'GNNGGGGGGG',
#         'GGNGGGGGGG',
#         'NNNGGGGGGG',
#         'NNGGGGGGGG',
#     ])
)

game.print_state(include_vanish_zone=True)

all_placements = MoveSearcher(game).get_all_placements()
print(f'Found {len(all_placements)} unique placements for piece')
all_placements

Current Board:
..........
...XXXX...
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
Active Piece: I at (3, 20) with rotation SPAWN
Next Piece: O
Hold Piece: None
Can Hold: True
Found 17 unique placements for piece


[{'state': (3, -2, 0),
  'sequence': [<ActionEnum.DROP: 5>],
  'bitmap': array([120,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        dtype=uint32),
  'lines_cleared': 0},
 {'state': (2, -2, 0),
  'sequence': [<ActionEnum.LEFT: 0>, <ActionEnum.DROP: 5>],
  'bitmap': array([60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0], dtype=uint32),
  'lines_cleared': 0},
 {'state': (4, -2, 0),
  'sequence': [<ActionEnum.RIGHT: 1>, <ActionEnum.DROP: 5>],
  'bitmap': array([240,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        dtype=uint32),
  'lines_cleared': 0},
 {'state': (4, 0, 1),
  'sequence': [<ActionEnum.ROTATE_CW: 2>, <ActionEnum.DROP: 5>],
  'bitmap': array([64, 64, 64, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0], dtype=u

In [15]:
i = 0

In [16]:
game.board.print_board(
    b_board=all_placements[i]['bitmap'])
i+=1

..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...XXXX...


# With env

In [197]:
from src.models import TetrisEnv

env = TetrisEnv(CONFIG, T_CONFIG)

state = env.reset()[0]
print(state.keys())
state

dict_keys(['boards', 'queues', 'queue_idx', 'placement_mask'])


{'boards': array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 1., ..., 0., 0., 0.],
         [0., 0., 1., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        ...,
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0.,

In [168]:
i = -1

In [169]:
i+=1
state['boards'][i]


array([[0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [192]:
import numpy as np

grid = state['boards'][i]
# Convert float32 occupancy grid to bitmap (col 0 = LSB)
row_ints = np.zeros(grid.shape[0], dtype=np.uint32)
for x in range(grid.shape[1]):
    row_ints |= (grid[:, x] > 0.5).astype(np.uint32) << x

game.board.color_map = False
game.board.print_board(
    b_board=row_ints,
    include_vanish_zone=True
)
i+=1

..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..XX......
.XX.......


In [200]:
queues = state['queues']
print(queues.shape)
print(queues) 

print()
queues_idx = state['queue_idx']
print(queues_idx.shape)
print(queues_idx) 

(2, 7, 8)
[[[0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]]]

(80,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0]


In [202]:
masks = state['placement_mask']
print(masks.shape)
print(masks) 


(80,)
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False]
